### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by joostf** [soraya2/minor-wafs#12]
Uncaught TypeError: Cannot read property 'url' of null
    at https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/data.js:60:60
    at Array.map (native)
    at Object.<anonymous> (https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/data.js:56:20)
    at https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/aja-min.js:1:1680
    at Array.forEach (native)
    at e (https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/aja-min.js:1:1658)
    at Object.trigger (https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/aja-min.js:1:1935)
    at XMLHttpRequest.m.onload (https://soraya2.github.io/minor-wafs/week2/rijksmuseumApi/static/js/aja-min.js:1:3281)

**Comment by soraya2** [comment]
added checks that check if the content is available first.
